### ISSUE TITLE
Security vulnerability in python dependencies

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [linkedbuildingdata/SummerSchoolOfLDAC#17]
this dependencies need to be updated:

> jupyterhub>=0.9.6

**Comment by deKlerk** [comment]
I already did it in the repository I'm using to test the installation process of the IJava kernel.
I'll update it here too.

**Comment by GeorgFerdinandSchneider** [comment]
Excellent; see branch #issue17_security

**Comment by GeorgFerdinandSchneider** [comment]
closed by https://github.com/linkedbuildingdata/SummerSchoolOfLDAC/commit/b7f1df6171021237de7b5eb91b071d55b9871dd8
