### ISSUE TITLE
Embed information in notebooks on packages

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [linkedbuildingdata/SummerSchoolOfLDAC#5]
Currently in mybinder.org it is necessary to install manually the non standard packages such as 
```xlrd``` and ```rdflib```. It would be good to add this information so mybinder.org installs them separately.

**Comment by deKlerk** [comment]
In the first notebook (check python setup), we need to install the necessary modules using:
`!pip install rdflib`
`!pip install xlrd`

Only after that can we use the `import` statements.

**Comment by GeorgFerdinandSchneider** [comment]
From @deKlerk:

From mybinder.org  all it should take is a requirements.txt at the root of the repo:

>We build a Docker image of your repository Binder will search for a dependency file, such as  equirements.txt or environment.yml, in the repository's root directory (more details on more complex  ependencies in documentation). The dependency files will be used to build a Docker image. If an  mage has already been built for the given repository, it will not be rebuilt. If a new commit has been made, the image will automatically be rebuilt.
